# Generated by Django 5.1.4 on 2026-03-08 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jobapplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('linkedin_count', models.IntegerField(default=0)),
                ('indeed_count', models.IntegerField(default=0)),
                ('naukari_count', models.IntegerField(default=0)),
            ],
        ),
    ]
